### ISSUE TITLE
Problem changing targeted time for countdown mode

### ISSUE THREAD

**Issue by justradojko** [wimbarelds/TimeCircles#118]
Hi,

I'm trying to make countdown timer where user can stop current timer (stop-button), change time and then start (start-button) it again with new targeted time, but I'm having some difficulties. I'm not sure if it is a bug or I'm doing something wrong? 

Timer is set with good targeted time just for the first time. Every other time, targeted time stays the same.

Bellow is the code that I'm using.
- timer initialization

``` javascript
var timerConfig = {
    "animation": "ticks",
    "bg_width": 0.4,
    "fg_width": 0.056,
    "start": false,
    "circle_bg_color": "#60686F",
    "time": {
        "Days": {
            "text": "Days",
            "color": "#FF5B00",
            "show": false
        },
        ...
    }
};
$('.countdown-timer').TimeCircles(timerConfig);
```
- action on start-button

``` javascript
$('.countdown-timer').attr('data-date', dateFormat);
$('.countdown-timer').TimeCircles().restart();
```
- action on stop-button

``` javascript
$('.countdown-timer').TimeCircles().stop();
$('.countdown-timer').removeAttr('data-date');
```

I would appreciate your response a lot.

Best regards,
Radojko

**Comment by wimbarelds** [comment]
Hi there, try to use .data('date', dateFormat) instead.

2016-06-23 14:21 GMT+02:00 justradojko notifications@github.com:

**Comment by justradojko** [comment]
It's working now. Thank you so much!
