### ISSUE TITLE
Change time dynamically

### ISSUE THREAD

**Issue by Ariakas** [wimbarelds/TimeCircles#2]
How can I change time when timer is running?
Couldn't find any sample.

**Comment by sukritchhabra** [comment]
Does this only work with the date attribute or can this be done by updating total_duration or timer attribute?

**Comment by wimbarelds** [comment]
It will also work with `data-timer`

**Comment by sukritchhabra** [comment]
This is my code:

```html
<div class="timer" data-timer="120"></div>
<button class="button" style="width:200px; height:200px; background-color: lightblue;">Click me</button>
```

```javascript
$('.timer').data('timer', 120).TimeCircles({
        "total_duration": 120,
        "count_past_zero": false,
        "use_background": false,
        "time": {
            "Days": {
                "show": false
            },
            "Hours": {
                "show": false
            },
            "Minutes": {
                "show": false
            },
            "Seconds": {
                "text": "Seconds",
                "color": "#FF9999",
                "show": true
            }
        }
    });

    $('.button').on('click', function(event) {
        var tmp = $(".timer").TimeCircles().getTime();
        tmp = tmp - 20;
        //tmp = tmp.toString();
        $(".timer").data('timer', tmp).TimeCircles().start();
    });
```

`.toString` is commented because that didn't work either. And the data-timer update isn't working either.

**Comment by wimbarelds** [comment]
Ah. I should have mentioned; for timers you'll want to use `.restart()` instead of `.start()`. Try that and it should work.

**Comment by sukritchhabra** [comment]
Yup! That worked. Thanks!

**Comment by sukritchhabra** [comment]
Still one problem with it though and it more of a UX issue:

When restart is called, so the clock start all over again just with a different time. So for ex: if `total_duration` was `100` and now I restart it with `50`, one would expect the clock to be half full like it would have been if we'd let the clock run and it had reached 50. 

But since we're calling `resatart();`, even though the clock now resets to 50, the clock also becomes full which I don't want it to be. Is there a workaround for this or am I just missing something?

**Comment by wimbarelds** [comment]
Can you link to a example page? It sounds like what you want might have something to do with the `total_duration` setting, but I'm not 100% sure what you mean. Example would be great.

**Comment by sukritchhabra** [comment]
I figured it out. You were right, it had to do with the `total_duration`. If with the restart you also pass the new time like this:
```javascript
$(".timer").data('timer', newTime).TimeCircles({
    "total_duration": newTime
}).restart();
```
it basically creates a new instance.

Thanks for all your help :)
