### ISSUE TITLE
[Question] How can I trigger an event when the Timer reaches 0?

### ISSUE THREAD

**Issue by oliveratgithub** [wimbarelds/TimeCircles#21]
Hi there,

Hope you can help me out with that: I am using the TimeCircles as a Countdown.

Now, when on the website and the counter reaches 00:00:00 - it starts counting up again (I think I am not using the newest version, will fix that later). Anyway - despite that behaviour, I want to trigger a jQuery event, namely Page Reload, when the counter reaches 0.

I tried working with the .end() event, but that seems not to work (or I implemented it wrongly):

``` javascript
$("#Countdown").TimeCircles().end(function(){
    window.location.reload(true)
});
```

From the documentation it refers to working with _addEventListener()_ - but honestly I am not familiar with that.

So asking you here: can you help me out with this and pointing me into the right direction for how to achieve a page reload via jQuery as soon as my TimeCircles() reaches 00:00:00? Thank you very much :)

**Comment by GrigoryanKaren** [comment]
I have many timecircles and i need event when stopwatch is over . 
AddListener is using to much memory.
Is there any alternative?

**Comment by wimbarelds** [comment]
Hello GrigoryanKaren,

When compared to the rest of TimeCircles, addListener uses extremely little memory *unless* you're doing something wrong (like continuously adding more and more listeners by accident).

**Comment by GrigoryanKaren** [comment]
thank you for response, I have like 200 timecircles or even more,maybe even 500, end js memory rize up to 300,000 K , (i have 8 GB RAM ) and eventually my page going very very slow. 
I am sure that i add for each instance one listener.

**Comment by wimbarelds** [comment]
Even in that case, adding listeners would be an absolute fraction of the CPU/Memory used by the animations/visualization. I'd venture to say that removing just 1 instance of TimeCircles would likely free up more CPU/Memory than a thousand listeners (Mind you, thats an estimate).
