### ISSUE TITLE
Object doesn't support this property or method

### ISSUE THREAD

**Issue by waldobuck** [wimbarelds/TimeCircles#25]
Awesome plugin!

However, while it works fine with Chrome, Firefox, and IE9, it does not work with IE8 and gives an error “Object doesn't support this property or method” and prevents the plugin from running properly.

While I realize GitHub does not support IE8 and below, is there a workaround or fix for this so users with IE8 can benefit from this plugin?

Thanks for your help.

Waldo Buck
www.CoolZips.com

**Comment by waldropnet** [comment]
The inclusion of the explorer canvas almost works.  The animation is blinking and cutoff at the edges.
