### ISSUE TITLE
remove "days" display

### ISSUE THREAD

**Issue by yuhao-nyc** [wimbarelds/TimeCircles#27]
Hi there, here I come back again (shamed).
I was trying to remove the 1(days) of the 4 time circles, so in the end will be only hours, minutes, seconds. I did successfully remove the display of "days" by using
 <script type="text/javascript">
            $(function() {
                //circles customizations
                $("#countdown").TimeCircles({
                    count_past_zero: false,
                     "bg_width": 1,
                     "fg_width": 0.07777776,
                     "circle_bg_color": "#c0cbcb",
                     "time": {
                        "Hours": {
                            "text": "Hrs",
                            "color": "#e7ebeb"
                        },
                        "Minutes": {
                            "text": "Min",
                            "color": "#e7ebeb"
                        },
                        "Seconds": {
                            "text": "Sec",
                            "color": "#e7ebeb"
                        }
                    }
                })
            });
        </script>
But more issues come out, my current site wanna it like a countdown timer, so when I have a 2 days countdown, my "time circle"  will hide the extra days, how can I add the extra days (which is most time 24 hours ) to hours circles? 
I hope I explained myself clear.
Thanks so much for help.

**Comment by Voodaii** [comment]
I've been having a bit of trouble with my attempt to hide the days circle. The "text" and "color" attributes work perfectly, but the "show" attribute seems to have no effect. Here is my code, am I doing something wrong?

var timeCircles = $(".someTimer").TimeCircles({ 

```
"time": {
    "Days": {            
        "text": "Days",
        "color": "#FFCC66",
        "show": false
    },
    "Hours": {
        "text": "Hours",
        "color": "#99CCFF",
        "show": true
    },
    "Minutes": {
        "text": "Minutes",
        "color": "#BBFFBB",
        "show": true
    },
    "Seconds": {
        "text": "Seconds",
        "color": "#FF9999",
        "show": true
    }
}
```

  });

Here is the full code:
[circleTimer.txt](https://github.com/wimbarelds/TimeCircles/files/377623/circleTimer.txt)

**Comment by yuhao-nyc** [comment]
I see everything looks OK from me. im not sure why it didnt work. 
maybe try not define the function with timeCircles? and in later part of your code its controlling with that function

**Comment by yuhao-nyc** [comment]
if still not working try change the show attributes in TimeCircles.js. might not be a great idea tho

**Comment by wimbarelds** [comment]
Can you please show a codepen or something alike where you have your full code? An example page I can look at?
