### ISSUE TITLE
How to make responsive?

### ISSUE THREAD

**Issue by Fatbat** [wimbarelds/TimeCircles#30]
While TimeCircles draws to fill 100% of its container when the page loads, if you resize the page and the container changes dimensions, TimeCircles remains at it's original dimensions and does not redraw itself.

Is there a way to update TimeCircles on screen resize?

I tried

```
$(window).resize(TimeCircles);
```

but that didn't do anything. Sorry to inundate you with questions :) Your help is greatly appreciated.

**Comment by kingRayhan** [comment]
how can I make it responsive with css media quary?

I want to show 4 circle in large screen and 2 circle in medium screen and one circle in small screen.

**Comment by MrHazimAli** [comment]
when resize, there is error inside console and timecircles did not responsive.. any help ?
error : 
![error](https://user-images.githubusercontent.com/6757574/29005090-47d91b7c-7b06-11e7-9bf4-45a511bb9a19.PNG)

code:
![code](https://user-images.githubusercontent.com/6757574/29005092-49a3ab16-7b06-11e7-9039-c67bebbf1843.PNG)

tq
