### ISSUE TITLE
Display a different message when timer reaches zero?

### ISSUE THREAD

**Issue by Fatbat** [wimbarelds/TimeCircles#31]
How would you go about displaying a different message in the middle of the circle when the timer reaches zero?

**Comment by jimfengyh** [comment]
Hi @wimbarelds  the suggestion you put earlier worked great if(total <= 0).
I was trying to achieve something like when the countdown ends, hide one box and show another, everything is working until I refresh the page, the previous box I'm trying to hide comes back. Seems like the if (total < =0) only works on the "moment" when countdown is over. any ideas? Thanks!

**Comment by wimbarelds** [comment]
Are you using `data-timer` or `data-date`?

**Comment by jimfengyh** [comment]
yes i am using data-date

**Comment by wimbarelds** [comment]
You can save the status in localStorage and check that before you initialize TimeCircles; that seems like the simplest solution.
