### ISSUE TITLE
Change data-timer

### ISSUE THREAD

**Issue by harmenzon** [wimbarelds/TimeCircles#52]
Hello. Thanks for this great plugin.
I am trying to change the data-timer value with Javascript or by changing the value of an input. So making it a variable. Can you please advice me how to change the value of the data-timer this way?
Thanks!

**Comment by 4cruzeta** [comment]
Hello, nice job.

`.addTime(5)` is working for me, but the previous:

`$('#Timer').data('timer', 20).TimeCircles().Restart();`

Is not working any more... is there way to use it?

Thanks.

**Comment by HagayAvisar1976** [comment]
when I change the data-timer the UI is not updated, why is that?
$(".stopWatch").TimeCircles({timer:<using param here>, start:false, time: { Days: { show: false }, Hours: { show: false }, Minutes:{show:false}}}).rebuild();
