### ISSUE TITLE
with data-timer not to display non-informative zero-filled circles

### ISSUE THREAD

**Issue by inferrna** [wimbarelds/TimeCircles#93]
For example http://git.wimbarelds.nl/TimeCircles/readme.php#func_start_stop - at start displayed 0 days and 0 hours (with thin line mean which part of twenty-four hours 900 seconds is) that is absolutely non-informative. It would be great to have an option for hiding these full-time empty circles.

**Comment by wimbarelds** [comment]
You can manually hide them using the configuration; a way to automate this isn't implemented and probably won't be unless I find time to create a "version 2"- which would be a near complete rewrite. At this point I am only really doing bug-fixes. Sorry :(

**Comment by inferrna** [comment]
> You can manually hide them using the configuration
Can you provide an example? With passing 
```js
{time:{'Days': {'show': false}}}
```
I see both hours and seconds circles displaying seconds progress.

> "version 2"- which would be a near complete rewrite
Then I also have another two feature requests - 
1. make possible to change timer value on fly, without recreating time_circles.
2. base circles on svg (d3 maybe), instead of canvas, with possibility for users to apply their own styles to circles.

**Comment by wimbarelds** [comment]
Ah, do you mean that when it's 0 minutes and 59 seconds, that the minute circle is showing nearly a full minute? If so, you're looking for

````json
{"animation": "ticks"}
````

**Comment by inferrna** [comment]
I found the problem - it was
```js
total_duration: "Minutes"
```
I'm in doubt, bug it or not, but this combo
```js
            $('#remain').TimeCircles({count_past_zero: false,
                                      total_duration: "Minutes",
                                      time:{'Hours':{'show': false},
                                            'Days':{'show': false},
                                          }
                                      });
```
Makes minutes circle works like always last minute, even it really isn't.
